SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";





-- --------------------------------------------------------


CREATE TABLE `UM_general_country` (
  `id` int NOT NULL,
  `country_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `dialing_code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `letters_2` text COLLATE utf8mb4_unicode_520_ci,
  `letters_3` text COLLATE utf8mb4_unicode_520_ci,
  `flag` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Dumping data for table `UM_general_country`
--

INSERT INTO `UM_general_country` (`id`, `country_name`, `dialing_code`, `letters_2`, `letters_3`, `flag`) VALUES
(1, 'Afghanistan', '[\"+93\"]', 'AF', 'AFG', 'af'),
(2, 'Åland Islands', '[\"+358 18\"]', 'AX', 'ALA', 'ax'),
(3, 'Albania', '[\"+355\"]', 'AL', 'ALB', 'al'),
(4, 'Algeria', '[\"+213\"]', 'DZ', 'DZA', 'dz'),
(5, 'American Samoa', '[\"+684\"]', 'AS', 'ASM\r\n', 'as'),
(6, 'Andorra', '[\"+376\"]', 'AD', 'AND', 'ad'),
(7, 'Angola', '[\"+244\"]', 'AO', 'AGO', 'ao'),
(8, 'Anguilla', '[\"+264\"]', 'AI', 'AIA', 'ai'),
(9, 'Antigua and Barbuda', '[\"+268\"]', 'AG', 'ATG', 'ag'),
(10, 'Argentina', '[\"+54\"]', 'AR', 'ARG', 'ar'),
(11, 'Armenia', '[\"+374\"]', 'AM', 'ARM', 'am'),
(12, 'Aruba', '[\"+297\"]', 'AW', 'ABW', 'aw'),
(13, 'Australia', '[\"+61\"]', 'AU', 'AUS', 'au'),
(14, 'Austria', '[\"+43\"]', 'AT', 'AUT', 'at'),
(15, 'Azerbaijan', '[\"+994\"]', 'AZ', 'AZE', 'az'),
(16, 'Bahamas', '[\"+1\"]', 'BS', 'BHS', 'bs'),
(17, 'Bahrain', '[\"+973\"]', 'BH', 'BHR', 'bh'),
(18, 'Bangladesh', '[\"+880\"]', 'BD', 'BGD', 'bd'),
(19, 'Barbados', '[\"+246\"]', 'BB', 'BRB', 'bb'),
(20, 'Belarus', '[\"+375\"]', 'BY', 'BLR', 'by'),
(21, 'Belgium', '[\"+32\"]', 'BE', 'BEL', 'be'),
(22, 'Belize', '[\"+501\"]', 'BZ', 'BLZ', 'bz'),
(23, 'Benin', '[\"+229\"]', 'BJ', 'BEN', 'bj'),
(24, 'Bermuda', '[\"+1\"]', 'BM', 'BMU', 'bm'),
(25, 'Bhutan', '[\"+975\"]', 'BT', 'BTN', 'bt'),
(26, 'Bolivia', '[\"+591\"]', 'BO', 'BOL', 'bo'),
(27, 'Bonaire', '[\"+599\"]', 'BQ', 'BES', 'bq'),
(28, 'Bosnia and Herzegovina', '[\"+387\"]', 'BA', 'BIH', 'ba'),
(29, 'Botswana', '[\"+267\"]', 'BW', 'BWA', 'bw'),
(30, 'Brazil', '[\"+55\"]', 'BR', 'BRA', 'br'),
(31, 'British Indian Ocean Territory', '[\"+246\"]', 'IO', 'IOT', 'io'),
(32, 'British Virgin Islands', '[\"+1\"]', NULL, NULL, NULL),
(33, 'Brunei', '[\"+673\"]', 'BN', 'BRN', 'bn'),
(34, 'Bulgaria', '[\"+359\"]', 'BG', 'BGR', 'bg'),
(35, 'Burkina Faso', '[\"+226\"]', 'BF', 'BFA', 'bf'),
(36, 'Burundi', '[\"+257\"]', 'BI', 'BDI', 'bi'),
(37, 'Cape Verde', '[\"+238\"]', 'CV', 'CPV', 'cv'),
(38, 'Cambodia', '[\"+855\"]', 'KH', 'KHM', 'kh'),
(39, 'Cameroon', '[\"+237\"]', 'CM', 'CMR', 'cm'),
(40, 'Canada', '[\"+1\"]', 'CA', 'CAN', 'ca'),
(41, 'Caribbean Netherlands', '[\"+599\"]', NULL, NULL, NULL),
(42, 'Cayman Islands', '[\"+345\"]', 'KY', 'CYM', 'ky'),
(43, 'Central African Republic', '[\"+236\"]', 'CF', 'CAF', 'cf'),
(44, 'Chad', '[\"+235\"]', 'TD', 'TCD', 'td'),
(45, 'Chile', '[\"+56\"]', 'CL', 'CHL', 'cl'),
(46, 'China', '[\"+86\"]', 'CN', 'CHN', 'cn'),
(47, 'Christmas Island', '[\"+61\"]', 'CX', 'CXR', 'cx'),
(48, 'Cocos (Keeling) Islands', '[\"+61\"]', 'CC', 'CCK', 'cc'),
(49, 'Colombia', '[\"+57\"]', 'CO', 'COL', 'co'),
(50, 'Comoros', '[\"+269\"]', 'KM', 'COM', 'km'),
(51, 'Democratic Republic of the Congo', '[\"+243\"]', 'CD', 'COD', 'cd'),
(52, 'Cook Islands', '[\"+682\"]', 'CK', 'COK', 'ck'),
(53, 'Costa Rica', '[\"+506\"]', 'CR', 'CRI', 'cr'),
(54, 'Côte d\'Ivoire', '[\"+225\"]', NULL, NULL, NULL),
(55, 'Croatia', '[\"+385\"]', 'HR', 'HRV', 'hr'),
(56, 'Cuba', '[\"+53\"]', 'CU', 'CUB', 'cu'),
(57, 'Curaçao', '[\"+599\"]', 'CW', 'CUW', 'cw'),
(58, 'Cyprus', '[\"+357\"]', 'CY', 'CYP', 'cy'),
(59, 'Czechia', '[\"+420\"]', 'CZ', 'CZE', 'cz'),
(60, 'Denmark', '[\"+45\"]', 'DK', 'DNK', 'dk'),
(61, 'Djibouti', '[\"+253\"]', 'DJ', 'DJI', 'dj'),
(62, 'Dominica', '[\"+767\"]', 'DM', 'DMA', 'dm'),
(63, 'Dominican Republic', '[\"+1\"]', 'DO', 'DOM', 'do'),
(64, 'Ecuador', '[\"+593\"]', 'EC', 'ECU', 'ec'),
(65, 'Egypt', '[\"+20\"]', 'EG', 'EGY', 'eg'),
(66, 'El Salvador', '[\"+503\"]', 'SV', 'SLV', 'sv'),
(67, 'Equatorial Guinea', '[\"+240\"]', 'GQ', 'GNQ', 'gq'),
(68, 'Eritrea', '[\"+291\"]', 'ER', 'ERI', 'er'),
(69, 'Estonia', '[\"+372\"]', 'EE', 'EST', 'ee'),
(70, 'Eswatini', '[\"+268\"]', 'SZ', 'SWZ', 'sz'),
(71, 'Ethiopia', '[\"+251\"]', 'ET', 'ETH', 'et'),
(72, 'Falkland Islands (Islas Malvinas)', '[\"+500\"]', 'FK', 'FLK', 'fk'),
(73, 'Faroe Islands', '[\"+298\"]', 'FO', 'FRO', 'fo'),
(74, 'Fiji', '[\"+679\"]', 'FJ', 'FJI', 'fj'),
(75, 'Finland', '[\"+358\"]', 'FI', 'FIN', 'fi'),
(76, 'France', '[\"+33\"]', 'FR', 'FRA', 'fr'),
(77, 'French Guiana', '[\"+594\"]', 'GF', 'GUF', 'gf'),
(78, 'French Polynesia', '[\"+689\"]', 'PF', 'PYF', 'pf'),
(79, 'Gabon', '[\"+241\"]', 'GA', 'GAB', 'ga'),
(80, 'Gambia', '[\"+220\"]', 'GM', 'GMB', 'gm'),
(81, 'Georgia', '[\"+995\"]', 'GE', 'GEO', 'ge'),
(82, 'Germany', '[\"+49\"]', 'DE', 'DEU', 'de'),
(83, 'Ghana', '[\"+233\"]', 'GH', 'GHA', 'gh'),
(84, 'Gibraltar', '[\"+350\"]', 'GI', 'GIB', 'gi'),
(85, 'Greece', '[\"+30\"]', 'GR', 'GRC', 'gr'),
(86, 'Greenland', '[\"+299\"]', 'GL', 'GRL', 'gl'),
(87, 'Grenada', '[\"+473\"]', 'GD', 'GRD', 'gd'),
(88, 'Guadeloupe', '[\"+590\"]', 'GP', 'GLP', 'gp'),
(89, 'Guam', '[\"+1\"]', 'GU', 'GUM', 'gu'),
(90, 'Guatemala', '[\"+502\"]', 'GT', 'GTM', 'gt'),
(91, 'Guernsey', '[\"+44\"]', 'GG', 'GGY', 'gg'),
(92, 'Guinea', '[\"+224\"]', 'GN', 'GIN', 'gn'),
(93, 'Guinea-Bissau', '[\"+245\"]', 'GW', 'GNB', 'gw'),
(94, 'Guyana', '[\"+592\"]', 'GY', 'GUY', 'gy'),
(95, 'Haiti', '[\"+509\"]', 'HT', 'HTI', 'ht'),
(96, 'Honduras', '[\"+504\"]', 'HN', 'HND', 'hn'),
(97, 'Hong Kong', '[\"+852\"]', 'HK', 'HKG', 'hk'),
(98, 'Hungary', '[\"+36\"]', 'HU', 'HUN', 'hu'),
(99, 'Iceland', '[\"+354\"]', 'IS', 'ISL', 'is'),
(100, 'India', '[\"+91\"]', 'IN', 'IND', 'in'),
(101, 'Indonesia', '[\"+62\"]', 'ID', 'IDN', 'id'),
(102, 'Iran', '[\"+98\"]', 'IR', 'IRN', 'ir'),
(103, 'Iraq', '[\"+964\"]', 'IQ', 'IRQ', 'iq'),
(104, 'Ireland', '[\"+353\"]', 'IE', 'IRL', 'ie'),
(105, 'Isle of Man', '[\"+44\"]', 'IM', 'IMN', 'im'),
(106, 'Israel', '[\"+972\"]', 'IL', 'ISR', 'il'),
(107, 'Italy', '[\"+39\"]', 'IT', 'ITA', 'it'),
(108, 'Jamaica', '[\"+876\"]', 'JM', 'JAM', 'jm'),
(109, 'Svalbard and Jan Mayen', '[\"+47\"]', NULL, NULL, NULL),
(110, 'Japan', '[\"+81\"]', 'JP', 'JPN', 'jp'),
(111, 'Jersey', '[\"+44\"]', 'JE', 'JEY', 'je'),
(112, 'Jordan', '[\"+962\"]', 'JO', 'JOR', 'jo'),
(113, 'Kazakhstan', '[\"+7\"]', 'KZ', 'KAZ', 'kz'),
(114, 'Kenya', '[\"+254\"]', 'KE', 'KEN', 'ke'),
(115, 'Kiribati', '[\"+686\"]', 'KI', 'KIR', 'ki'),
(116, 'North Korea', '[\"+850\"]', 'KP', 'PRK', 'kp'),
(117, 'South Korea', '[\"+82\"]', 'KR', 'KOR', 'kr'),
(118, 'Kosovo', '[\"+383\"]', NULL, NULL, NULL),
(119, 'Kuwait', '[\"+965\"]', 'KW', 'KWT', 'kw'),
(120, 'Kyrgyzstan', '[\"+996\"]', 'KG', 'KGZ', 'kg'),
(121, 'Laos', '[\"+856\"]', NULL, NULL, NULL),
(122, 'Latvia', '[\"+371\"]', 'LV', 'LVA', 'lv'),
(123, 'Lebanon', '[\"+961\"]', 'LB', 'LBN', 'lb'),
(124, 'Lesotho', '[\"+266\"]', 'LS', 'LSO', 'ls'),
(125, 'Liberia', '[\"+231\"]', 'LR', 'LBR', 'lr'),
(126, 'Libya', '[\"+218\"]', 'LY', 'LBY', 'ly'),
(127, 'Liechtenstein', '[\"+423\"]', 'LI', 'LIE', 'li'),
(128, 'Lithuania', '[\"+370\"]', 'LT', 'LTU', 'lt'),
(129, 'Luxembourg', '[\"+352\"]', 'LU', 'LUX', 'lu'),
(130, 'Macao', '[\"+853\"]', 'MO', 'MAC', 'mo'),
(131, 'Madagascar', '[\"+261\"]', 'MG', 'MDG', 'mg'),
(132, 'Malawi', '[\"+265\"]', 'MW', 'MWI', 'mw'),
(133, 'Malaysia', '[\"+60\"]', 'MY', 'MYS', 'my'),
(134, 'Maldives', '[\"+960\"]', 'MV', 'MDV', 'mv'),
(135, 'Mali', '[\"+223\"]', 'ML', 'MLI', 'ml'),
(136, 'Malta', '[\"+356\"]', 'MT', 'MLT', 'mt'),
(137, 'Marshall Islands', '[\"+692\"]', 'MH', 'MHL', 'mh'),
(138, 'Martinique', '[\"+596\"]', 'MQ', 'MTQ', 'mq'),
(139, 'Mauritania', '[\"+222\"]', 'MR', 'MRT', 'mr'),
(140, 'Mauritius', '[\"+230\"]', 'MU', 'MUS', 'mu'),
(141, 'Mayotte', '[\"+262\"]', 'YT', 'MYT', 'yt'),
(142, 'Mexico', '[\"+52\"]', 'MX', 'MEX', 'mx'),
(143, 'Federated States of Micronesia', '[\"+691\"]', 'FM', 'FSM', 'fm'),
(144, 'Moldova', '[\"+373\"]', 'MD', 'MDA', 'md'),
(145, 'Monaco', '[\"+377\"]', 'MC', 'MCO', 'mc'),
(146, 'Mongolia', '[\"+976\"]', 'MN', 'MNG', 'mn'),
(147, 'Montenegro', '[\"+382\"]', 'ME', 'MNE', 'me'),
(148, 'Morocco', '[\"+212\"]', 'MA', 'MAR', 'ma'),
(149, 'Mozambique', '[\"+258\"]', 'MZ', 'MOZ', 'mz'),
(150, 'Myanmar', '[\"+95\"]', 'MM', 'MMR', 'mm'),
(151, 'Nagorno-Karabakh', '[\"+994\"]', NULL, NULL, NULL),
(152, 'Namibia', '[\"+264\"]', 'NA', 'NAM', 'na'),
(153, 'Nauru', '[\"+674\"]', 'NR', 'NRU', 'nr'),
(154, 'Nepal', '[\"+977\"]', 'NP', 'NPL', 'np'),
(155, 'Netherlands', '[\"+31\"]', 'NL', 'NLD', 'nl'),
(156, 'Nevis', '[\"+869\"]', NULL, NULL, NULL),
(157, 'New Caledonia', '[\"+687\"]', 'NC', 'NCL', 'nc'),
(158, 'New Zealand', '[\"+64\"]', 'NZ', 'NZL', 'nz'),
(159, 'Nicaragua', '[\"+505\"]', 'NI', 'NIC', 'ni'),
(160, 'Niger', '[\"+227\"]', 'NE', 'NER', 'ne'),
(161, 'Nigeria', '[\"+234\"]', 'NG', 'NGA', 'ng'),
(162, 'Niue', '[\"+683\"]', 'NU', 'NIU', 'nu'),
(163, 'Norfolk Island', '[\"+672\"]', 'NF', 'NFK', 'nf'),
(164, 'North Macedonia', '[\"+389\"]', NULL, NULL, NULL),
(165, 'Northern Cyprus', '[\"+597\"]', NULL, NULL, NULL),
(166, 'Northern Ireland', '[\"+44\"]', NULL, NULL, NULL),
(167, 'Northern Mariana Islands', '[\"+1\"]', 'MP', 'MNP', 'mp'),
(168, 'Norway', '[\"+47\"]', 'NO', 'NOR', 'no'),
(169, 'Oman', '[\"+968\"]', 'OM', 'OMN', 'om'),
(170, 'Pakistan', '[\"+92\"]', 'PK', 'PAK', 'pk'),
(171, 'Palau', '[\"+680\"]', 'PW', 'PLW', 'pw'),
(172, 'Palestine', '[\"+970\"]', 'PS', 'PSE', 'ps'),
(173, 'Panama', '[\"+507\"]', 'PA', 'PAN', 'pa'),
(174, 'Paraguay', '[\"+595\"]', 'PY', 'PRY', 'py'),
(175, 'Peru', '[\"+51\"]', 'PE', 'PER', 'pe'),
(176, 'Philippines', '[\"+63\"]', 'PH', 'PHL', 'ph'),
(177, 'Pitcairn Islands', '[\"+64\"]', 'PN', 'PCN', 'pn'),
(178, 'Poland', '[\"+48\"]', 'PL', 'POL', 'pl'),
(179, 'Portugal', '[\"+351\"]', 'PT', 'PRT', 'pt'),
(180, 'Puerto Rico', '[\"+1\"]', 'PR', 'PRI', 'pr'),
(181, 'Qatar', '[\"+974\"]', 'QA', 'QAT', 'qa'),
(182, 'Réunion', '[\"+262\"]', 'RE', 'REU', 're'),
(183, 'Romania', '[\"+40\"]', 'RO', 'ROU', 'ro'),
(184, 'Russia', '[\"+7\"]', 'RU', 'RUS', 'ru'),
(185, 'Rwanda', '[\"+250\"]', 'RW', 'RWA', 'rw'),
(186, 'Saint Barthélemy', '[\"+590\"]', 'BL', 'BLM', 'bl'),
(187, 'Saint Helena', '[\"+290\"]', 'SH', 'SHN', 'sh'),
(188, 'Saint Kitts and Nevis', '[\"+869\"]', 'KN', 'KNA', 'kn'),
(189, 'Saint Lucia', '[\"+758\"]', 'LC', 'LCA', 'lc'),
(190, 'Saint Martin', '[\"+599\"]', 'MF', 'MAF', 'mf'),
(191, 'Saint Pierre and Miquelon', '[\"+508\"]', 'PM', 'SPM', 'pm'),
(192, 'Saint Vincent and the Grenadines', '[\"+784\"]', 'VC', 'VCT', 'vc'),
(193, 'Samoa', '[\"+685\"]', 'WS', 'WSM', 'ws'),
(194, 'San Marino', '[\"+378\"]', 'SM', 'SMR', 'sm'),
(195, 'São Tomé and Príncipe', '[\"+239\"]', 'ST', 'STP', 'st'),
(196, 'Saudi Arabia', '[\"+966\"]', 'SA', 'SAU', 'sa'),
(197, 'Senegal', '[\"+221\"]', 'SN', 'SEN', 'sn'),
(198, 'Serbia', '[\"+381\"]', 'RS', 'SRB', 'rs'),
(199, 'Seychelles', '[\"+248\"]', 'SC', 'SYC', 'sc'),
(200, 'Sierra Leone', '[\"+232\"]', 'SL', 'SLE', 'sl'),
(201, 'Singapore', '[\"+65\"]', 'SG', 'SGP', 'sg'),
(202, 'Sint Eustatius', '[\"+599\"]', NULL, NULL, NULL),
(203, 'Slovakia', '[\"+421\"]', 'SK', 'SVK', 'sk'),
(204, 'Slovenia', '[\"+386\"]', 'SI', 'SVN', 'si'),
(205, 'Solomon Islands', '[\"+677\"]', 'SB', 'SLB', 'sb'),
(206, 'Somalia', '[\"+252\"]', 'SO', 'SOM', 'so'),
(207, 'South Africa', '[\"+27\"]', 'ZA', 'ZAF', 'za'),
(208, 'South Georgia and the South Sandwich Islands', '[\"+500\"]', 'GS', 'SGS', 'gs'),
(209, 'South Ossetia', '[\"+7\"]', NULL, NULL, NULL),
(210, 'South Sudan', '[\"+211\"]', 'SS', 'SSD', 'ss'),
(211, 'Spain', '[\"+34\"]', 'ES', 'ESP', 'es'),
(212, 'Sri Lanka', '[\"+94\"]', 'LK', 'LKA', 'lk'),
(213, 'Sudan', '[\"+249\"]', 'SD', 'SDN', 'sd'),
(214, 'Suriname', '[\"+597\"]', 'SR', 'SUR', 'sr'),
(215, 'Svalbard', '[\"+47\"]', 'SJ', 'SJM', 'sj'),
(216, 'Sweden', '[\"+46\"]', 'SE', 'SWE', 'se'),
(217, 'Switzerland', '[\"+41\"]', 'CH', 'CHE', 'ch'),
(218, 'Syria', '[\"+963\"]', 'SY', 'SYR', 'sy'),
(219, 'Taiwan', '[\"+886\"]', 'TW', 'TWN', 'tw'),
(220, 'Tajikistan', '[\"+992\"]', 'TJ', 'TJK', 'tj'),
(221, 'Tanzania', '[\"+255\"]', 'TZ', 'TZA', 'tz'),
(222, 'Thailand', '[\"+66\"]', 'TH', 'THA', 'th'),
(223, 'Timor-Leste', '[\"+670\"]', 'TL', 'TLS', 'tl'),
(224, 'Togo', '[\"+228\"]', 'TG', 'TGO', 'tg'),
(225, 'Tokelau', '[\"+690\"]', 'TK', 'TKL', 'tk'),
(226, 'Tonga', '[\"+676\"]', 'TO', 'TON', 'to'),
(227, 'Transnistria', '[\"+373\"]', NULL, NULL, NULL),
(228, 'Trinidad and Tobago', '[\"+868\"]', 'TT', 'TTO', 'tt'),
(229, 'Tristan da Cunha', '[\"+290\"]', NULL, NULL, NULL),
(230, 'Tunisia', '[\"+216\"]', 'TN', 'TUN', 'tn'),
(231, 'Turkey', '[\"+90\"]', 'TR', 'TUR', 'tr'),
(232, 'Turkmenistan', '[\"+993\"]', 'TM', 'TKM', 'tm'),
(233, 'Turks and Caicos Islands', '[\"+1\"]', NULL, NULL, NULL),
(234, 'Tuvalu', '[\"+688\"]', 'TV', 'TUV', 'tv'),
(235, 'Uganda', '[\"+256\"]', 'UG', 'UGA', 'ug'),
(236, 'Ukraine', '[\"+380\"]', 'UA', 'UKR', 'ua'),
(237, 'United Arab Emirates', '[\"+971\"]', 'AE', 'ARE', 'ae'),
(238, 'United Kingdom', '[\"+44\"]', 'GB', 'GBR', 'gb'),
(239, 'United States', '[\"+1\"]', 'US', 'USA', 'us'),
(240, 'Uruguay', '[\"+598\"]', 'UY', 'URY', 'uy'),
(241, 'Uzbekistan', '[\"+998\"]', 'UZ', 'UZB', 'uz'),
(242, 'Vanuatu', '[\"+678\"]', 'VU', 'VUT', 'vu'),
(243, 'Vatican City', '[\"+379\"]', NULL, NULL, NULL),
(244, 'Venezuela', '[\"+58\"]', 'VE', 'VEN', 've'),
(245, 'Vietnam', '[\"+84\"]', 'VN', 'VNM', 'vn'),
(246, 'Wallis and Futuna', '[\"+681\"]', 'WF', 'WLF', 'wf'),
(247, 'Yemen', '[\"+967\"]', 'YE', 'YEM', 'ye'),
(248, 'Zambia', '[\"+260\"]', 'ZM', 'ZMB', 'zm'),
(249, 'Zanzibar', '[\"+255\"]', NULL, NULL, NULL),
(250, 'Zimbabwe', '[\"+263\"]', 'ZW', 'ZWE', 'zw');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `UM_general_country`
--
ALTER TABLE `UM_general_country`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `UM_general_country`
--
ALTER TABLE `UM_general_country`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=257;
COMMIT;